### ISSUE TITLE
"sabcmd delete blabla" says "Error: Delete command requires a second argument."

### ISSUE THREAD

**Issue by sanderjo** [fetzerms/sabcmd#2]
Based on

```
   Examples:
     - sabcmd status
     - sabcmd add http://here.is.my.nzb/ubuntu14_04.nzb
     - sabcmd add /tmp/here.is.my.nzb/ubuntu14_04.nzb
     - sabcmd delete ubuntu14_04

```

I tried this, but the delete does not work:

```
$ ./sabcmd status
+----[ SABcmd ]------------------------------------------------>
| Currently enqueued nzbs:
| 
|    (   1 ) Submarine
|    (   2 ) ubuntu
|    (   3 ) ubuntu
|    (   4 ) ubuntu
|    (   5 ) ubuntu
| 
| Current transfer speed: 1.3 M/s
+-------------------------------------------------------------->

$ ./sabcmd delete ubuntu
Error: Delete command requires a second argument.

$ ./sabcmd delete 2
Error: Delete command requires a second argument.
```

And:

```
$ ./sabcmd delete -t ubuntu
./sabcmd: line 428: [: missing `]'
Removing
| SABnzbd failed to delete nzb ubuntu.

$ ./sabcmd delete -t 2
./sabcmd: line 428: [: missing `]'
Removing
| SABnzbd failed to delete nzb 2.

```

**Comment by sanderjo** [comment]
Ah, this works better: first delete double entries:

```
$ ./sabcmd status
+----[ SABcmd ]------------------------------------------------>
| Currently enqueued nzbs:
| 
|    (   1 ) Submarine
|    (   2 ) ubuntu
| 
| Current transfer speed: 0 /s
+-------------------------------------------------------------->


$ ./sabcmd delete -t ubuntu
./sabcmd: line 428: [: missing `]'
Removing
| SABnzbd deleted NZB ubuntu (SABnzbd_nzo_XkkeDY) successfully.


$ ./sabcmd status
+----[ SABcmd ]------------------------------------------------>
| Currently enqueued nzbs:
| 
|    (   1 ) Submarine
| 
| Current transfer speed: 0 /s
+-------------------------------------------------------------->
```

Still a strange `./sabcmd: line 428: [: missing `]'`

**Comment by fetzerms** [comment]
I updated the README.md (somehow i had old examples in it), and fixed the errors regarding the wrong brackets. Can you please check if it works as you expected?

**Comment by sanderjo** [comment]
Can you also update the Examples in sabcmd.sh itself?

**Comment by sanderjo** [comment]
It still gets confused with >1 entry with the same name:

```
sander@flappie:~/git/sabcmd$ ./sabcmd status
+----[ SABcmd ]------------------------------------------------>
| Currently enqueued nzbs:
| 
|    (   1 ) Submarine
|    (   2 ) ubuntu
|    (   3 ) ubuntu
| 
| Current transfer speed: 0 /s
+-------------------------------------------------------------->


sander@flappie:~/git/sabcmd$ ./sabcmd delete -t ubuntu
+----[ SABcmd ]------------------------------------------------>
| 
| SABnzbd failed to delete nzb ubuntu.
| 
+-------------------------------------------------------------->


sander@flappie:~/git/sabcmd$ ./sabcmd status
+----[ SABcmd ]------------------------------------------------>
| Currently enqueued nzbs:
| 
|    (   1 ) Submarine
|    (   2 ) ubuntu
|    (   3 ) ubuntu
| 
| Current transfer speed: 0 /s
+-------------------------------------------------------------->
```

And number does not work:

```
sander@flappie:~/git/sabcmd$ ./sabcmd delete -t 2
+----[ SABcmd ]------------------------------------------------>
| 
| SABnzbd failed to delete nzb 2.
| 
+-------------------------------------------------------------->
sander@flappie:~/git/sabcmd$ 
sander@flappie:~/git/sabcmd$ ./sabcmd status
+----[ SABcmd ]------------------------------------------------>
| Currently enqueued nzbs:
| 
|    (   1 ) Submarine
|    (   2 ) ubuntu
|    (   3 ) ubuntu
| 
| Current transfer speed: 0 /s
+-------------------------------------------------------------->
```

**Comment by sanderjo** [comment]
With a unique name it works:

```
sander@flappie:~/git/sabcmd$ ./sabcmd status
+----[ SABcmd ]------------------------------------------------>
| Currently enqueued nzbs:
| 
|    (   1 ) Submarine
|    (   2 ) ubuntu
| 
| Current transfer speed: 0 /s
+-------------------------------------------------------------->
sander@flappie:~/git/sabcmd$ 


sander@flappie:~/git/sabcmd$ ./sabcmd delete -t ubuntu
+----[ SABcmd ]------------------------------------------------>
| 
| SABnzbd deleted NZB ubuntu (SABnzbd_nzo_yz1AGu) successfully.
| 
+-------------------------------------------------------------->


sander@flappie:~/git/sabcmd$ ./sabcmd status
+----[ SABcmd ]------------------------------------------------>
| Currently enqueued nzbs:
| 
|    (   1 ) Submarine
| 
| Current transfer speed: 0 /s
+-------------------------------------------------------------->
```

**Comment by sanderjo** [comment]
Maybe make it possible to use the sequence number ("2") or present the nzo name ("SABnzbd_nzo_yz1AGu")?

**Comment by fetzerms** [comment]
I'm on it.

Would you expect it to delete _all_ duplicates (if using the nzb name), or just the first one?

**Comment by sanderjo** [comment]
Difficult to answer. Certainly not all. So: the first one?

How about also allowing the sequence number? So

```
./sabcmd delete --number 2
```

**Comment by fetzerms** [comment]
Yes. I currently have it delete everything that matches now. 

I am already at implementing using the sequence number and NZO name.

**Comment by fetzerms** [comment]
Should be fixed. I will close the issue after updating the readme file

**Comment by fetzerms** [comment]
Issue fixed. Please re-open if any other issues are found.
